version: '3.2'

services:
  apigateway:
    image: kapilshekharraina/apigateway:latest
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 768M
        reservations:
          cpus: '0.25'
          memory: 512M
    #container_name: apigateway
    environment:
        - apigateway.activeprofiles=startup, dev
    ports:
      - "8080:8080"
      - "8854:8854"
 
networks:
 default:
  external:
   name: ms-chassis-nw-swarm