version: '2.2'

services:
  jaeger:
    image: 'jaegertracing/all-in-one:1.17'
    #container_name: redis
    mem_reservation: 512M
    mem_limit: 768M
    cpus: ".50"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - '5775:5775/udp'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '16686:16686'
      - '14268:14268'
      - '14250:14250'
      - '9411:9411'

networks:
 default:
  external:
   name: ms-chassis-nw