--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: jaeger
    version: v1
  name: jaeger
spec: 
  ports: 
    - 
      name: http
      port: 16686
      targetPort: 16686
  selector: 
    app: jaeger
    version: v1
  type: NodePort