--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: jaeger
    version: v1
  name: jaeger
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: jaeger
      version: v1
  template: 
    metadata: 
      labels: 
        app: jaeger
        version: v1
    spec: 
      containers: 
        - 
          image: jaegertracing/all-in-one:1.17
          imagePullPolicy: IfNotPresent
          name: jaeger
          ports: 
          - containerPort: 5775   
          - containerPort: 6831  
          - containerPort: 6832  
          - containerPort: 5778  
          - containerPort: 16686  #serve frontend
          - containerPort: 14268  
          - containerPort: 14250 
          - containerPort: 9411 

          env:
            - name:  COLLECTOR_ZIPKIN_HTTP_PORT
              value: "9411"
          resources:
            requests:
                memory: "256Mi"
                cpu: "100m"
            limits:
                memory: "512Mi"
                cpu: "400m"