--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: rabbitmq-master
    version: v1
  name: rabbitmq-master
spec: 
  ports: 
    - 
      name: http
      port: 15672
      targetPort: 15672
    - 
      name: rabbitmq5672
      port: 5672
      targetPort: 5672
    - 
      name: rabbitmq4369
      port: 4369
      targetPort: 4369
    - 
      name: rabbitmq5671
      port: 5671
      targetPort: 5671
    - 
      name: rabbitmq15671
      port: 15671
      targetPort: 15671
    - 
      name: rabbitmq25671
      port: 25671
      targetPort: 25671
  selector: 
    app: rabbitmq
    version: v1
  type: NodePort