--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: mongo
    version: v1
  name: mongo
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: mongo
      version: v1
  template: 
    metadata: 
      labels: 
        app: mongo
        version: v1
    spec: 
      containers: 
        - 
          image: mongo
          imagePullPolicy: IfNotPresent
          name: mongo
          ports: 
          - containerPort: 27017    

          env:
            - name:  MONGO_INITDB_ROOT_USERNAME
              value: "root"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "root"
          volumeMounts:
            - mountPath: /data/db
              name: mongo-data
          resources:
            requests:
                memory: "512Mi"
                cpu: "100m"
            limits:
                memory: "1024Mi"
                cpu: "400m"
      volumes:
       - name: mongo-data
         persistentVolumeClaim:
            claimName: mongodb-pvc
#      volumes:
#       - name: mongo-data
#         hostPath:
#            path: /work/sharedmount/mongo/data
#            type: DirectoryOrCreate