--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: mongo
    version: v1
  name: mongo
spec: 
  ports: 
    - 
      name: http
      port: 27017
      targetPort: 27017
  selector: 
    app: mongo
    version: v1
  type: NodePort