--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: zipkin
    version: v1
  name: zipkin
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: zipkin
      version: v1
  template: 
    metadata: 
      labels: 
        app: zipkin
        version: v1
    spec: 
      containers: 
        - 
          image: openzipkin/zipkin
          imagePullPolicy: IfNotPresent
          name: zipkin
          ports: 
          - containerPort: 9411    

          env:
            - name:  STORAGE_TYPE
              value: "mem"
          resources:
            requests:
                memory: "256Mi"
                cpu: "100m"
            limits:
                memory: "512Mi"
                cpu: "400m"