--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: zipkin
    version: v1
  name: zipkin
spec: 
  ports: 
    - 
      name: http
      port: 9411
      targetPort: 9411
  selector: 
    app: zipkin
    version: v1
  type: NodePort