kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: masterclusterrole
subjects:
- kind: ServiceAccount
  name: user01
  namespace: default
roleRef:
  kind: ClusterRole
  name: masterclusterrole
  apiGroup: rbac.authorization.k8s.io