--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: eureka
    version: v1
  name: eureka
spec: 
  ports: 
    - 
      name: http
      port: 8761
      targetPort: 8761
  selector: 
    app: eureka
    version: v1
  type: NodePort