--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: consul-server-bootstrap
    version: v1
  name: consul-server-bootstrap
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: consul-server-bootstrap
      version: v1
  template: 
    metadata: 
      labels: 
        app: consul-server-bootstrap
        version: v1
    spec: 
      containers: 
        - 
          image: consul:latest
          imagePullPolicy: IfNotPresent
          name: consul-server-bootstrap
          command: ["consul"]
          args: ["agent","-server","-bootstrap", "-ui", "-client", "0.0.0.0","-data-dir","/etc/data"]
          ports: 
          - containerPort: 8400
          - containerPort: 8500 #Http
          - containerPort: 8600
          resources:
            requests:
                memory: "256Mi"
                cpu: "200m"
            limits:
                memory: "512Mi"
                cpu: "400m"
          volumeMounts:
            - mountPath: /etc/data
              name: consul-data        
      volumes:
       - name: consul-data
         persistentVolumeClaim:
            claimName: consul-pvc