--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: jenkins
    version: v1
  name: jenkins
spec: 
  ports: 
    - 
      name: http
      port: 8900
      targetPort: 8080
    - 
      name: http50000
      port: 50000
      targetPort: 50000
  selector: 
    app: jenkins
    version: v1
  type: NodePort