--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: kafka
    broker: b1
  name: kafka1
spec: 
  ports: 
    - 
      name: tcpkafkab1
      port: 9094
      targetPort: 9094
      protocol: TCP
  #clusterIP: None    
  #type: NodePort
  selector: 
    app: kafka
    broker: b1
# On Host Outside Cluster run :  kubectl port-forward svc/kafka1 9094:9094    
--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: kafka
    broker: b2
  name: kafka2
spec: 
  ports: 
    - 
      name: tcpkafkab2
      port: 9095
      targetPort: 9095
      protocol: TCP
  #clusterIP: None
  #type: NodePort
  selector: 
    app: kafka
    broker: b2
    
# On Host Outside Cluster run :  kubectl port-forward svc/kafka2 9095:9095 