--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: zookeeper
    version: v1
  name: zookeeper
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: zookeeper
      version: v1
  template: 
    metadata: 
      labels: 
        app: zookeeper
        version: v1
    spec: 
      containers: 
        - 
          image: "wurstmeister/zookeeper"
          imagePullPolicy: IfNotPresent
          name: zookeeper
          ports: 
          - containerPort: 2181  
          env:
            - name:  jute.maxbuffer
              value: "2147483648"          
          volumeMounts:
            - mountPath: "/var/run/docker.sock"
              name: dockersock
          resources:
            requests:
                memory: "256Mi"
                cpu: "200m"
            limits:
                memory: "512Mi"
                cpu: "400m" 
      volumes:
       - name: dockersock
         hostPath:
            path: "/var/run/docker.sock"