--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: configserver
    version: v1
  name: configserver
spec: 
  ports: 
    - 
      name: http
      port: 8888
      targetPort: 8888
  selector: 
    app: configserver
    version: v1