version: '2.2'

services:
  apigateway:
    image: kapilshekharraina/apigateway:latest
    mem_reservation: 512M
    mem_limit: 768M
    cpus: ".75"
    #container_name: apigateway
    environment:
       apigateway.activeprofiles: startup, dev
       #configserver.zone.url: http://host.docker.internal:8888
    ports:
      - "8080:8080"
      - "8854:8854"
 
networks:
 default:
  external:
   name: ms-chassis-nw