--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: redis
    version: v1
  name: redis
spec: 
  ports: 
    - 
      name: http
      port: 6379
      targetPort: 6379
  selector: 
    app: redis
    version: v1
  type: NodePort