apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-nfs-redis-pv
spec:
  capacity:
    storage: 1Gi # This size is used to match a volume to a tenents claim
  accessModes:
    - ReadWriteMany # Access modes are defined below
  persistentVolumeReclaimPolicy: Recycle # Reclaim policies are defined below
#  storageClassName: immediate
  nfs:
    server: 10.0.2.11 # Please change this to your NFS server
    path: /mnt/k8smnt/redis # Please change this to the relevant share
    