--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: mysql
    version: v1
  name: mysql
spec: 
  ports: 
    - 
      name: http
      port: 3306
      targetPort: 3306
  selector: 
    app: mysql
    version: v1
  type: NodePort