--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: cloudconfigserver
    version: v1
  name: cloudconfigserver
spec: 
  ports: 
    - 
      name: http
      port: 8888
      targetPort: 8888
    - 
      name: httpactuator
      port: 8889
      targetPort: 8889
  selector: 
    app: cloudconfigserver
    version: v1
  type: NodePort