--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: grafana
    version: v1
  name: grafana
spec: 
  ports: 
    - 
      name: http
      port: 3000
      targetPort: 3000
  selector: 
    app: grafana
    version: v1
  type: NodePort