--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: eureka-1
    version: v1
  name: eureka-1
spec: 
  ports: 
    - 
      name: http
      port: 8761
      targetPort: 8761
  selector: 
    app: eureka-1
    version: v1
  type: NodePort
  
--- 
 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: eureka-2
    version: v1
  name: eureka-2
spec: 
  ports: 
    - 
      name: http
      port: 8762
      targetPort: 8762
  selector: 
    app: eureka-2
    version: v1
  type: NodePort