--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: eureka-1
    version: v1
  name: eureka-1
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: eureka-1
      version: v1
  template: 
    metadata: 
      labels: 
        app: eureka-1
        version: v1
    spec: 
      containers: 
        - 
          image: "kapilshekharraina/eurekaserver:latest"
          imagePullPolicy: Always
          name: eureka-1
          ports: 
          - containerPort: 8761    

          env:
            - name:  eureka.server.activeprofiles
              value: "startup, dev"
            - name: eureka.server.port
              value: "8761"
            - name: eureka.server.hostname
              value: "eureka-1"
            - name: eureka.peer.url
              value: "http://eureka-2:8762/eureka"
          resources:
            requests:
                memory: "256Mi"
                cpu: "200m"
            limits:
                memory: "768Mi"
                cpu: "400m" 
              
--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: eureka-2
    version: v1
  name: eureka-2
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: eureka-2
      version: v1
  template: 
    metadata: 
      labels: 
        app: eureka-2
        version: v1
    spec: 
      containers: 
        - 
          image: "kapilshekharraina/eurekaserver:latest"
          imagePullPolicy: Always
          name: eureka-1
          ports: 
          - containerPort: 8762

          env:
            - name:  eureka.server.activeprofiles
              value: "startup, dev"
            - name: eureka.server.port
              value: "8762"
            - name: eureka.server.hostname
              value: "eureka-2"
            - name: eureka.peer.url
              value: "http://eureka-1:8762/eureka"
          resources:
            requests:
                memory: "256Mi"
                cpu: "200m"
            limits:
                memory: "768Mi"
                cpu: "400m"                   
