--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: mysqlss
    version: v1
  name: mysqlss
spec: 
  ports: 
    - 
      name: http
      port: 3306
      targetPort: 3306
  selector: 
    statefulset.kubernetes.io/pod-name: mysqlss-1
  type: NodePort