--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: mysqlheadless
    version: v1
  name: mysqlheadless
spec: 
  ports: 
    - 
      name: http
      port: 3306
#      targetPort: 3306
  clusterIP: None
  selector: 
    app: mysqlss
    version: v1
#  type: NodePort