version: '3.1'
#volumes:
#   prometheus_data: {}
services:
  prometheus:
    #image: kapilshekharraina/prometheus:latest
    #user: root
    build:
      context: .
      dockerfile: Dockerfile
    #mem_reservation: 512M
    #mem_limit: 768M
    #cpus: ".75"
    #container_name: prometheus
   # volumes:
   # - ./config/prometheus.yml:/etc/prometheus/config/prometheus.yml
   # - ./data:/prometheus
    
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=31d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

    ports:
      - "9090:9090"

networks:
 default:
  external:
   name: ms-chassis-nw