--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: vault
    version: v1
  name: vault
spec: 
  ports: 
    - 
      name: http
      port: 8200
      targetPort: 8200
  selector: 
    app: vault
    version: v1
  type: NodePort