#https://www.bogotobogo.com/DevOps/Docker/Docker-Vault-Consul.php
version: '2.2'
services:

  vault:
    build:
      context: ./vault
      dockerfile: Dockerfile
    #container_name: vault
    
    #cpu_percent: 10
    mem_reservation: 512M
    mem_limit: 768M
    cpus: ".75"
    ports:
      - 8200:8200
    #volumes:
      #- ./vault/config:/vault/config
     # - ./vault/policies:/vault/policies
     # - ./vault/data:/vault/data
    #  - ./vault/logs:/vault/logs
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
    command: server -config=/vault/config/vault-config.json
    cap_add:
      - IPC_LOCK
networks:
 default:
  external:
   name: ms-chassis-nw