--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    component: spekt8
  name: spekt8
spec: 
  ports: 
    - 
      name: http
      port: 3000
      targetPort: 3000
  selector: 
    component: spekt8
  type: NodePort