version: "3.2"

services:
  turbine:
    image: kapilshekharraina/turbine:latest 
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 768M
        reservations:
          cpus: '0.50'
          memory: 512M
    #container_name: turbine
    environment:
        - turbine.activeprofiles=startup, dev
    ports:
      - "9093:9093"
      - "8855:8855"
 
networks:
 default:
  external:
   name: ms-chassis-nw-swarm