#https://www.bogotobogo.com/DevOps/Docker/Docker-Vault-Consul.php
version: '3.2'
services:

  vault:
    image: kapilshekharraina/vault:latest
    #build:
    #  context: ./vault
    #  dockerfile: Dockerfile
    #container_name: vault
    deploy:
      resources:
        limits:
          cpus: ".50"
          memory: 768M
        reservations:
          cpus: ".25"
          memory: 512M
    ports:
      - 8200:8200
    #volumes:
      #- ./vault/config:/vault/config
     # - ./vault/policies:/vault/policies
     # - ./vault/data:/vault/data
    #  - ./vault/logs:/vault/logs
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
    command: server -config=/vault/config/vault-config.json
    cap_add:
      - IPC_LOCK
      
networks:
 default:
  external:
   name: ms-chassis-nw-swarm