version: "3.3"
services:
  rabbitmq-master:
    image: kapilshekharraina/rabbitmq:latest
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 768M
        reservations:
          cpus: '0.25'
          memory: 512M
    ports:
     - "15672:15672"
     - "5672:5672"
     - "4369:4369"
     - "5671:5671"
     - "15671:15671"
     - "25671:25671"
    environment:
        RABBITMQ_ERLANG_COOKIE: "secret string"
        RABBITMQ_NODENAME:  "rabbitmq-master"
    #volumes:
    #  - ./config/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
    #  - ./config/definitions.json:/etc/rabbitmq/definitions.json
        
  rabbitmq-worker:
    image: kapilshekharraina/rabbitmq:latest
    #build: 
    #    context: .
    #    dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 768M
        reservations:
          cpus: '0.25'
          memory: 512M
    #container_name: rabbitmq-worker
    #image: rabbitmq:3-management
    environment:
        RABBITMQ_ERLANG_COOKIE: "secret string"
        RABBITMQ_NODENAME:  "rabbitmq-worker"
    #volumes:
    #  - ./config/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
   #   - ./config/definitions.json:/etc/rabbitmq/definitions.json
    depends_on:
     - rabbitmq-master
 
networks:
 default:
  external:
   name: ms-chassis-nw-swarm